import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nunito_Sans, Poetsen_One } from 'next/font/google';

import "./globals.css";

const nunito = Nunito_Sans({ subsets: ['latin'], variable: '--font-nunito' });
const poetsen = Poetsen_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poetsen',
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thoraya adel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased bg-black bg-linear-to-r from-indigo-500/10 via-violet-500/20 to-fuchsia-500/30`}
      >
        {children}

      </body>
    </html>
  );
}
